apiVersion: v1
kind: Service
metadata:
  name: esewa-service
spec:
  type: NodePort
  selector:
    app: esewa
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080